#!/bin/bash
#==============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of Flight Directory.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Flight Directory is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight Directory. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight Directory, please visit:
# https://github.com/openflighthpc/flight-directory
#==============================================================================
dir="$(cd $(dirname "$0") && pwd)"
cmd=$1
case $cmd in
    user-add)
	if [[ "$* " == *" --group "* || "$*" == *" --random "* ]]; then
	    uname=$2
	    args=()
	    for a in "$@"; do
		if [ "$a" == "--random" ]; then
		    if [ -x "${dir}"/password-generator ]; then
			password="$("${dir}"/password-generator)"
		    else
			args+=($a)
		    fi
		elif [ "$a" == "--group" ]; then
		    grab_group=true
		elif [ "$grab_group" ]; then
		    group="$a"
		    unset grab_group
		else
		    args+=($a)
		fi
	    done
	    tmpf=$(mktemp /tmp/userware-ipa-wrapper.XXXXXXX)
	    ipa --no-prompt "${args[@]}" > $tmpf
	    rc=$?
	    if [ $rc == 0 -a -n "$group" ]; then
		ipa --no-prompt group-add-member $group --users=$uname &>/dev/null
		rc=$?
		if [ $rc != 0 ]; then
		    ipa user-del $uname &>/dev/null
		fi
	    fi
	    if [ $rc == 0 -a -n "${password}" ]; then
		echo "${password}" | ipa passwd $uname &>/dev/null
		rc=$?
		if [ $rc != 0 ]; then
		    ipa user-del $uname &>/dev/null
		else
		    sed -i 's/^Password: False/Password: true/g' $tmpf
		    echo "  Random password: ${password}" >> $tmpf
		fi
	    fi
	    cat $tmpf 
	    rm -f $tmpf
	    exit $rc
	else
	    exec ipa --no-prompt "$@"
	fi
	;;
    *)
	exec ipa --no-prompt "$@"
	;;
esac
